'use client';

import { useMemo, useRef, useState } from 'react';
import { Loader2, UploadCloud } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';

import { localeNames } from '@/config/locale';
import { themes } from '@/config/theme/themes';
import { Button } from '@/shared/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/shared/components/ui/card';
import { Input } from '@/shared/components/ui/input';
import { Label } from '@/shared/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/shared/components/ui/select';
import { Textarea } from '@/shared/components/ui/textarea';
import {
  getDefaultOpenClawPromptTemplate,
  OPENCLAW_PROMPT_PLACEHOLDER_HELP,
} from '@/shared/services/landing-config';

const DEFAULT_OPTION = 'default';

function getVariantKey(locale: string, theme: string) {
  return `${locale}:${theme}`;
}

export function LandingBundleManager({ locale }: { locale: string }) {
  const isZh = locale === 'zh';
  const router = useRouter();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [slug, setSlug] = useState('');
  const [title, setTitle] = useState('');
  const [bundleLocale, setBundleLocale] = useState(locale);
  const [bundleTheme, setBundleTheme] = useState(DEFAULT_OPTION);
  const [file, setFile] = useState<File | null>(null);
  const [loading, setLoading] = useState(false);
  const [lastResult, setLastResult] = useState<{
    slug: string;
    indexPath: string;
    variantKey: string;
  } | null>(null);

  const variantKey = useMemo(
    () => getVariantKey(bundleLocale || DEFAULT_OPTION, bundleTheme),
    [bundleLocale, bundleTheme]
  );

  const promptPreview = useMemo(
    () => getDefaultOpenClawPromptTemplate(locale === 'zh' ? 'zh' : 'en'),
    [locale]
  );

  async function handleUpload() {
    if (!slug.trim()) {
      toast.error(isZh ? '请先填写 bundle slug' : 'Bundle slug is required');
      return;
    }

    if (!file) {
      toast.error(isZh ? '请先选择 zip 文件' : 'Please select a zip file');
      return;
    }

    const formData = new FormData();
    formData.append('file', file);
    formData.append('slug', slug.trim());
    formData.append('title', title.trim());
    formData.append('locale', bundleLocale || DEFAULT_OPTION);
    formData.append('theme', bundleTheme);
    formData.append('variantKey', variantKey);

    try {
      setLoading(true);

      const response = await fetch('/api/admin/landing/upload-bundle', {
        method: 'POST',
        body: formData,
      });

      const result = await response.json();
      if (!response.ok || result.code !== 0) {
        throw new Error(result.message || 'Upload failed');
      }

      setLastResult({
        slug: result.data.bundle.slug,
        indexPath: result.data.bundle.indexPath,
        variantKey: result.data.variantKey,
      });
      toast.success(
        isZh
          ? 'HTML bundle 已上传并写入映射'
          : 'HTML bundle uploaded and mapped successfully'
      );
      setFile(null);
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
      router.refresh();
    } catch (error: any) {
      toast.error(error.message || (isZh ? '上传失败' : 'Upload failed'));
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-8 md:max-w-4xl">
      <Card>
        <CardHeader>
          <CardTitle>
            {isZh ? '上传首页 HTML Bundle' : 'Upload Landing HTML Bundle'}
          </CardTitle>
          <CardDescription>
            {isZh
              ? '上传 OpenClaw 生成的 zip，系统会自动解压到 public/landing-bundles，并写入语言 / 主题映射。'
              : 'Upload a zip generated by OpenClaw. It will be extracted into public/landing-bundles and mapped to the selected locale/theme variant.'}
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-5">
          <div className="grid gap-5 md:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="bundle-slug">
                {isZh ? 'Bundle Slug' : 'Bundle Slug'}
              </Label>
              <Input
                id="bundle-slug"
                value={slug}
                onChange={(event) => setSlug(event.target.value)}
                placeholder="home-zh-divine"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="bundle-title">
                {isZh ? '展示标题' : 'Display Title'}
              </Label>
              <Input
                id="bundle-title"
                value={title}
                onChange={(event) => setTitle(event.target.value)}
                placeholder={
                  isZh ? '中文神圣主题首页' : 'English Divine Homepage'
                }
              />
            </div>
          </div>

          <div className="grid gap-5 md:grid-cols-2">
            <div className="space-y-2">
              <Label>{isZh ? '语言变体' : 'Locale Variant'}</Label>
              <Select value={bundleLocale} onValueChange={setBundleLocale}>
                <SelectTrigger className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value={DEFAULT_OPTION}>
                    {isZh ? '默认语言' : 'Default Locale'}
                  </SelectItem>
                  {Object.entries(localeNames).map(([value, label]) => (
                  <SelectItem key={value} value={value}>
                      {String(label)}
                  </SelectItem>
                ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>{isZh ? '主题变体' : 'Theme Variant'}</Label>
              <Select value={bundleTheme} onValueChange={setBundleTheme}>
                <SelectTrigger className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value={DEFAULT_OPTION}>
                    {isZh ? '默认主题' : 'Default Theme'}
                  </SelectItem>
                  {themes.map((theme) => (
                    <SelectItem key={theme.name} value={theme.name}>
                      {theme.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="bundle-file">
              {isZh ? 'Zip 文件' : 'Zip File'}
            </Label>
            <Input
              id="bundle-file"
              ref={fileInputRef}
              type="file"
              accept=".zip,application/zip"
              onChange={(event) =>
                setFile(event.target.files?.[0] || null)
              }
            />
          </div>

          <div className="rounded-lg border border-dashed border-border/80 bg-muted/30 p-4 text-sm">
            <div className="font-medium">
              {isZh ? '当前映射 key' : 'Current Mapping Key'}: {variantKey}
            </div>
            <p className="text-muted-foreground mt-1">
              {isZh
                ? '系统会写入 landing_home_bundle_variants，并自动启用 HTML bundle section。'
                : 'The uploader writes into landing_home_bundle_variants and automatically enables the homepage HTML bundle section.'}
            </p>
          </div>

          <Button
            type="button"
            onClick={handleUpload}
            disabled={loading}
            className="inline-flex items-center gap-2"
          >
            {loading ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <UploadCloud className="h-4 w-4" />
            )}
            {isZh ? '上传并发布 bundle' : 'Upload and Publish Bundle'}
          </Button>

          {lastResult ? (
            <div className="rounded-lg border bg-background p-4 text-sm">
              <div className="font-medium">
                {isZh ? '最近一次上传' : 'Latest Upload'}
              </div>
              <div className="text-muted-foreground mt-2 space-y-1">
                <div>slug: {lastResult.slug}</div>
                <div>variant: {lastResult.variantKey}</div>
                <div>entry: {lastResult.indexPath}</div>
              </div>
            </div>
          ) : null}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>
            {isZh ? 'OpenClaw 提示词编写要点' : 'OpenClaw Prompt Guidance'}
          </CardTitle>
          <CardDescription>
            {isZh
              ? '下面是当前推荐模板。你也可以直接在本页下方的设置表单里继续修改正式提示词。'
              : 'This is the recommended starter template. You can keep editing the final prompt in the settings form on this same page.'}
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2">
            <div className="rounded-lg border bg-muted/20 p-4 text-sm">
              <div className="font-medium">
                {isZh ? '运行时占位符' : 'Runtime Placeholders'}
              </div>
              <div className="text-muted-foreground mt-2 space-y-1">
                <div>{'{{locale}}'}: {OPENCLAW_PROMPT_PLACEHOLDER_HELP.locale}</div>
                <div>{'{{theme_label}}'} / {'{{theme_description}}'}</div>
                <div>{'{{appearance}}'}: light | dark</div>
                <div>{'{{business_context}}'}</div>
                <div>{'{{section_goal}}'}</div>
              </div>
            </div>

            <div className="rounded-lg border bg-muted/20 p-4 text-sm">
              <div className="font-medium">
                {isZh ? 'bundle 页面应读取的查询参数' : 'Query Params the Bundle Should Read'}
              </div>
              <div className="text-muted-foreground mt-2 space-y-1">
                <div>?locale=en</div>
                <div>?theme=divine</div>
                <div>?appearance=dark</div>
              </div>
            </div>
          </div>

          <Textarea
            value={promptPreview}
            readOnly
            className="min-h-80 font-mono text-xs"
          />
        </CardContent>
      </Card>
    </div>
  );
}
